### ISSUE TITLE
Set unfilled blanks like [this], with highlighting

### ISSUE THREAD

**Issue by kemitchell** [commonform/commonform-docx#5]
@anseljh how do you feel about this? The underscore-blanks at the moment are alright, but I often find they're too short or too long to be practical on print-and-fill forms. Square brackets are definitely a convention in the practice. I see highlighting a fair amount of the time, and appreciate how it keeps blanks from getting lost in the sea of text.

**Comment by anseljh** [comment]
Yes, I think it's a good idea. It would be nice if the blank carried some information, so brackets with the blank name would be helpful. Additional highlighting might be a bonus, at least worth testing to see how we feel about it after dogfooding.

**Comment by kemitchell** [comment]
Implemented by 7426cf3a4d75149480f69f6de02db7cd44b48ee4

**Comment by kemitchell** [comment]
Published in commonform-docx@0.10.0. Landed in CI in commonform-cli@0.7.1.
